# Generated by Django 4.0.5 on 2022-06-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='a_student',
            fields=[
                ('student_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='student_id')),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('year', models.FloatField()),
                ('area', models.CharField(max_length=100)),
            ],
        ),
    ]
